import {createInitialState,step,STAGES,type Course,type RunState} from '../../shared/rock-run.js';
import {writeFileSync} from 'node:fs';
import { searchCrossing } from '../analysis/rock-run-search.js';
import { PATTERN_SETTINGS, MOTION_PER_TICK, TEMPLATE_TAKEOFF_X, PILLAR_WIDTH, FIRST_PILLAR_MIN_FRAMES,
  FIRST_WIRE_MIN_DELAY_TICKS, MAX_WIRE_REFIRE_Y, distancePerMotionFrame } from '../../shared/rock-run-config.js';
import { REFERENCE as R } from '../../shared/rock-run-reference.js';
import type { RunPattern } from '../../shared/rock-run-patterns.js';

function solve(c:Course,stage:number,x=TEMPLATE_TAKEOFF_X,motionClock=0) {
  return searchCrossing({...createInitialState(),phase:'playing',stage,x,motionClock},c.platforms[1].x,c,
    {minWireDelayTicks:FIRST_WIRE_MIN_DELAY_TICKS,maxAirbornePressY:MAX_WIRE_REFIRE_Y});
}
const catalog:(Omit<RunPattern,'inputs'> & {inputs:boolean[]})[]=[];
for(let stage=0;stage<6;stage++){
 const dx=distancePerMotionFrame(stage);
 const edgeApproachOffsets=Array.from({length:Math.min(24,dx-2)+1},(_,i)=>-Math.min(24,dx-2)+i);
 for(const count of [1,2,3]){
 let found=0;
 const spacings=new Set<number>();
 search:for(const frames of [18,20,22,24,26,28])for(const first of [10,12,14,16])for(const tail of [16,18,20,22]){
  if(spacings.has(frames))continue;
  const anchors=Array.from({length:count},(_,i)=>({x:dx*first+i*dx*frames,width:PILLAR_WIDTH}));
  const gap=anchors[count-1].x+dx*tail;
  const c={platforms:[{x:-1000,end:0,y:R.ground},{x:gap,end:gap+dx*28,y:R.ground}],anchors,coins:[],ends:[Infinity,Infinity,Infinity,Infinity,Infinity,Infinity]};
  const result=solve(c,stage);
  if(result.status!=='found')continue;
  const a=result.actions;
  if(first<FIRST_PILLAR_MIN_FRAMES||a.findIndex((hit,i)=>i>=2&&hit)<2+FIRST_WIRE_MIN_DELAY_TICKS)continue;
  const takeoffOffsets=[-dx+2,-dx*.75,-dx*.5,-dx*.25,TEMPLATE_TAKEOFF_X,0,...edgeApproachOffsets];
  if(!takeoffOffsets.every(x=>[0,.25,.5,.75,.99].every(clock=>solve(c,stage,x,clock).status==='found')))continue;
  if(count>1&&anchors.some((_,omit)=>solve({...c,anchors:anchors.filter((_,i)=>i!==omit)},stage).status!=='not-found'))continue;
  console.log(JSON.stringify({stage,count,first,frames,tail,gap,ok:!!a}));
  if(a){
   let s={...createInitialState(),phase:'playing' as const,stage,x:TEMPLATE_TAKEOFF_X} as RunState;
   const gold:{x:number;y:number}[]=[];
   for(const hit of a){
    s=step(s,{hit},c);
    if(s.x>60&&s.x<gap-40&&s.y>45&&s.y<430&&s.x-(gold.at(-1)?.x??-1000)>dx*4)gold.push({x:s.x,y:s.y-15});
   }
   catalog.push({stage,kind:'wire',anchors:anchors.map(a=>a.x),gap,gold,inputs:a});
   spacings.add(frames);
   if(++found===(count===1?1:2))break search;
  }
 }
 if(!found)throw Error(`No mandatory ${count}-pillar pattern for stage ${stage}`);
 }
 let s={...createInitialState(),phase:'playing' as const,stage,x:0} as RunState;
 const flight:{x:number;y:number}[]=[];
 const empty={platforms:[],anchors:[],coins:[],ends:Array(6).fill(Infinity)};
 for(let t=0;t<100;t++){
  s=step(s,{hit:t===0},empty);flight.push({x:s.x,y:s.y-15});
  if(s.y>=R.ground&&s.motion!.dy<0)break;
 }
 const reach=s.x;
 for(const [kind,ratio] of [['short',.5],['jump',.75],['edge',1]] as const){
  const gap=reach*ratio-dx+TEMPLATE_TAKEOFF_X;
  const gold=flight.filter((p,i)=>i%8===0&&p.x>50&&p.x<gap-40).map(p=>({x:p.x+TEMPLATE_TAKEOFF_X,y:p.y}));
  catalog.push({stage,kind,anchors:[],gap,gold,inputs:flight.map((_,i)=>i===0)});
 }
}
writeFileSync(new URL('../../shared/rock-run-patterns.ts',import.meta.url),
  '// Generated by games/server/scripts/generate-rock-run-patterns.ts.\n'
  + 'export const GENERATED_SETTINGS = '+JSON.stringify(PATTERN_SETTINGS)+';\n'
  + 'export interface RunPattern { stage:number; kind:string; anchors:number[]; gap:number; gold:{x:number;y:number}[]; inputs:string }\n'
  + 'export const RUN_PATTERNS:RunPattern[] = [\n'
  + catalog.map(p=>JSON.stringify({...p,inputs:p.inputs.map((hit:boolean)=>hit?'1':'0').join('')})).join(',\n')
  + '\n];\n');
